My Portfolio: Desktop Version
DanielAD10/My-Portfolio pull request #4
Opened 2023-05-11 23:12 UTC by DanielAD10

PR Description

Project Name: My Portfolio
Key Feature: Desktop Version
Tech: Built with HTML & CSS

In this PR,

Modify styling to be responsive on desktop
Add some changes in index.html

Thank you for reviewing my code

2023-05-11 23:52 UTC, IngDavidTM requested changes
## Hi @DanielAD10 🙋‍♂️, 

Good job so far!
You have done well reaching this point of the milestone 🤝 . But there are some issues that you still need to work on to go to the next project but you are almost there!

<img src="https://media2.giphy.com/media/31Q36EHJ7C5ZoIMw79/giphy.gif"/>

## Top highlight 🎯
- The Pull Request follows the GitHub Flow ✅ 
- The PR title and description are professional and descriptive ✅ 
- Linters are working properly ✅ 

## Suggested changes

- [x] _Check the comments under the review._ ⬇

## Optional suggestions

_Every comment with the [OPTIONAL] prefix won't stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better. Some of them were simply missed by the previous reviewer and addressing them will really improve your application._

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561)  you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2023-05-11 23:52 UTC, IngDavidTM commented on style.css
- [ ] Your work on the desktop version of your portfolio is impressive :+1: :100:. However, ensuring that the design adheres to the same background images as the Figma template is essential. Failure to do so can result in a disjointed design that could negatively impact the project's usability and aesthetic appeal. Therefore, please review the background images in your portfolio and add any necessary ones to ensure consistency with the Figma template, as required by the project :+1:.

**Your design**

![Screenshot from 2023-05-11 18-39-59](https://github.com/DanielAD10/My-Portfolio/assets/105117832/75bcd2dd-390d-4c6c-9be4-4ad5093f5af9)

![Screenshot from 2023-05-11 18-42-07](https://github.com/DanielAD10/My-Portfolio/assets/105117832/82558723-9143-449c-a6cb-5442526f323f)

![Screenshot from 2023-05-11 18-43-06](https://github.com/DanielAD10/My-Portfolio/assets/105117832/bb921818-2fd6-4048-a092-73404c43d8ec)

**Figma**

![Screenshot from 2023-05-11 18-41-00](https://github.com/DanielAD10/My-Portfolio/assets/105117832/bd7ac35c-bf7d-4bed-8bc7-d1ddf6671052)

![Screenshot from 2023-05-11 18-41-48](https://github.com/DanielAD10/My-Portfolio/assets/105117832/207d6a5f-9b7c-41ad-ad03-bd30a0fe2497)

![Screenshot from 2023-05-11 18-42-55](https://github.com/DanielAD10/My-Portfolio/assets/105117832/03881e85-e59e-4798-a5be-853d9c11f64c)

2023-05-11 23:52 UTC, IngDavidTM commented on style.css
> +  }
- [ ] To ensure consistency with the Figma template, please align the text "I'm always..." to the middle of the form. This is important to maintain the overall design and ensure that the project meets the desired aesthetic standards :+1:. 

**Your design**

![Screenshot from 2023-05-11 18-43-06](https://github.com/DanielAD10/My-Portfolio/assets/105117832/8f1e8c1a-b5b4-4e54-8775-16f82d36d461)

**Figma**

![Screenshot from 2023-05-11 18-42-55](https://github.com/DanielAD10/My-Portfolio/assets/105117832/7f51b8b7-5e96-4d2c-979e-2da2104f9886)

2023-05-12 18:56 UTC, Qoosim approved these changes
#  *Status: Approved* :tada: :heavy_check_mark: 

Hi @DanielAD10, 

Your project is complete!  There is nothing else to say other than... it's time to merge it :shipit: 
Congratulations! 🎉 

## Highlights
-  No linter errors. :heavy_check_mark: 
-  Good README file. :heavy_check_mark: 
-  Correct GitHub Flow. :heavy_check_mark: 

![](https://camo.githubusercontent.com/54a5d803a138b5a1a1242a607e4c1192c852cab8c591c1ddcaa33d06b51560f6/68747470733a2f2f6d656469612e67697068792e636f6d2f6d656469612f686c516559335062684833692f67697068792e676966)

## Optional suggestions

_Every comment with the [OPTIONAL] prefix won't stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better. Some of them were simply missed by the previous reviewer and addressing them will really improve your application._

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561)  you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2023-05-12 18:59 UTC, merged