My-Portfolio: Poppup Detail View
DanielAD10/My-Portfolio pull request #8
Opened 2023-05-25 03:30 UTC by DanielAD10

PR Description

Project Name: My-Portfolio
Tech: Built with HTML, CSS & JavaScript

In this PR,

Add Mobile detail view and Desktop detail view in index.html
Style both detail view in style.css
Modify Project Modals with dynamics html and js

Thank you for reviewing my code.

2023-05-25 07:56 UTC, abdulhamiid requested changes
# Status: Required Changes :recycle:
Hi Team 👋, 
![](https://media.giphy.com/media/UdaSUYClr92cjWpeVx/giphy.gif)
Good job so far!
There are some issues that you still need to work on to go to the next project but you are almost there! :running_man: :runner: 
<FEEL FREE TO CHANGE THIS MESSAGE TO YOUR PERSONAL WORDS>

## Highlights 🌟

- ✔️ Descriptions are descriptive
- ✔️ Linters checks are passing
- ✔️ Use GitHub Flow
- ✔️ Meaningful commit messages.

## Required Changes ♻️
_Please kindly check the comments under the review._

[REQUIRED] - I'm unable to add a comment to your readme. so kindly check the required changes below 🤗

Please let's fix the broken link shown below: 👇 
![image](https://github.com/DanielAD10/My-Portfolio/assets/78251927/2ba707b3-4463-4ba2-b0bd-38c5f3c4ceb2)

Let's avoid broken links in our readme file for a professional repository. 💪

## Optional suggestions 🤷‍♂️
_Every comment with the [OPTIONAL] prefix is not crucial enough to stop the approval of this PR. However, I strongly recommend you take them into account as they can make your code better._
Cheers and Happy coding!👏👏👏

## Important Notes 📝
- Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
- Please, remember to tag me in your question so I can receive the notification.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2023-05-25 07:56 UTC, abdulhamiid commented on index.html
> +
According to the [project requirements](https://github.com/microverseinc/curriculum-html-css/blob/main/portfolio/8_popup.md), please kindly implement the following: 🤗💪

- In order to associate each project with the `popup window` details,
  - You need to use **a JavaScript array to store all of the information for all projects**. 🛠
  - For each project you need to store the following pieces of data in a JavaScript object, at a minimum: name, description, featured image, technologies, link to live version, link to source.

```javascript
const projects = [{
    name: "Submarine game",
    description: "A Phaser3 platform game built as part of the Microverse JavaScript program.",
    image: "link_to_image.jpg",
    technologies: ["Phaser3", "JavaScript", "Jest"],
    link: "link_to_live_version.com",
}]
```
Kindly modify the background of the popup so that it matches the template
- According to the template, the background is `transparent` and `blurry` 🛠

Your design
![image](https://github.com/DanielAD10/My-Portfolio/assets/78251927/825384cb-4097-4845-83c6-d45b95eb6208)

Figma
![image](https://github.com/DanielAD10/My-Portfolio/assets/78251927/ea018098-89b6-4ce1-947c-0432553fd603)

Mobile (Your design)
![image](https://github.com/DanielAD10/My-Portfolio/assets/78251927/02da372b-3616-496b-82f7-b9360bd9ce2b)

Mobile (Figma)
![image](https://github.com/DanielAD10/My-Portfolio/assets/78251927/c920ade0-eaec-4f11-8ad3-a3b3f79672d5)

- Please let's adjust the spacing `margin/padding` on top, right, bottom, and left in the [Mobile & Desktop] design to ensure that the popup window is positioned at the center of the page to match the template as much as possible.

[OPTIONAL] - It would be nice if you disable the scroll effect on the `body` when the pop-window appears
![image](https://github.com/DanielAD10/My-Portfolio/assets/78251927/8ed1bf4c-4b26-46c5-93b1-2a87cef71e95)

2023-05-25 07:56 UTC, abdulhamiid commented on index.html
> +                    </div>
Your design
![image](https://github.com/DanielAD10/My-Portfolio/assets/78251927/67b04548-f2f1-4e52-9855-abe07a844eac)

Figma
![image](https://github.com/DanielAD10/My-Portfolio/assets/78251927/b7b18a8d-90ee-47b9-8746-ca5041bfe993)

- Please kindly adjust the layout of the content of the button to match the provided template on Figma 👀🤗
- Kindly increase the font weight of the title `Keeping track of hundreds of components` to stick to the design as much as possible

2023-05-27 12:23 UTC, Munsa1 approved these changes
Hi @DanielAD10, 
![congratulations-1](https://github.com/DanielAD10/My-Portfolio/assets/81932478/1ca9eefe-313a-4333-beed-4add71b154f2)

Your project is complete!  There is nothing else to say other than... it's time to merge it :shipit: 
Congratulations! 🎉 

## Highlights
Made Requested Changes :heavy_check_mark: 


## Optional suggestions
- [ ] Kindly consider making your popup fully responsive by ensuring that when the user opens up the pop-up in mobile view when they change the screen size to desktop view, so should the pop-up without any glitches. Currently, this is how it shows when a user changes the screen size of the popup from mobile to desktop view. In order for it to display properly, the user has to reload the page and then open the popup again. It would be nice if you could fix this.
![image](https://github.com/DanielAD10/My-Portfolio/assets/81932478/344f5167-ebdd-4cb3-9390-5be3bad1ceb5)

_Every comment with the [OPTIONAL] prefix won't stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better. Some of them were simply missed by the previous reviewer and addressing them will really improve your application._

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561)  you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2023-05-27 12:27 UTC, merged